blog/urls.py
from django.urls import path
from django.urls.conf import include

from blog.views import article_list_view, article_detail_view, home_view, article_create_view, tag_list_view, \
    tag_detail_view, tag_create_view, tag_edit_view, tag_delete_view, topic_list_view, topic_create_view, \
    topic_detail_view, topic_edit_view, topic_delete_view, article_like_count_view, article_dislike_count_view, \
    toggle_dislike_view, toggle_like_view, article_archive_view, article_edit_view, article_view_count_view, \
    article_comments_view, article_add_comment_view, article_series_list_view, \
    article_series_detail_view, article_series_get_next_sequence_number_view

app_name = 'blog'

urlpatterns = [
    path('', home_view, name='index'),
    path('articles/', include([
        path('', article_list_view, name='article_list'),
        path('create', article_create_view, name='article_create'),
        path('<str:slug>/',
             include([
                 path('', article_detail_view, name='article_detail'),
                 path('edit', article_edit_view, name='article_edit'),
                 path('archive', article_archive_view, name='article_archive'),
                 path('like_count', article_like_count_view, name='article_like_count'),
                 path('dislike_count', article_dislike_count_view, name='article_dislike_count'),
                 path('toggle_like/', toggle_like_view, name='toggle_like'),
                 path('toggle_dislike/', toggle_dislike_view, name='toggle_dislike'),
                 path('view_count/', article_view_count_view, name='article_view_count'),
                 path('comments', article_comments_view, name='article_comments'),
                 path('add_comment', article_add_comment_view, name='article_add_comment')

             ])
             ),
        path('article_series/', include([
            path('', article_series_list_view, name='article_series_list'),
            path('<str:slug>/', include([
                path('', article_series_detail_view, name='article_series_detail'),
                path('get_next_sequence_number', article_series_get_next_sequence_number_view,
                     name='article_series_get_next_sequence_number')
            ]))
        ])),
        path('tags/', include([
            path('', tag_list_view, name='tag_list'),
            path('create', tag_create_view, name='tag_create'),
            path('<str:slug>/', include([
                path('', tag_detail_view, name='tag_detail'),
                path('edit', tag_edit_view, name='tag_edit'),
                path('delete', tag_delete_view, name='tag_delete'),
            ]))
        ])),
        path('topics/', include([
            path('', topic_list_view, name='topic_list'),
            path('create', topic_create_view, name='topic_create'),
            path('<str:slug>/', include([
                path('', topic_detail_view, name='topic_detail'),
                path('edit', topic_edit_view, name='topic_edit'),
                path('delete', topic_delete_view, name='topic_delete'),
            ]))
        ]))
    ]))
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('content.urls', namespace='content')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('arcus/', include('arcus.urls', namespace='arcus')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('users/', include('django.contrib.auth.urls', )),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'schir.dev admin'

blog/models.py
from typing import Union, Tuple

from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.db import models, transaction
from django.db.models import UniqueConstraint
from django.utils import timezone
from django.utils.html import strip_tags
from django.utils.text import Truncator
from django.utils.translation import gettext_lazy as _

from blog.utils.model_utils import generate_slug_from_title
from common.models import BaseModel

User = get_user_model()


class InteractionType(models.TextChoices):
    LIKE = 'like', 'Like'
    DISLIKE = 'dislike', 'Dislike'


class Article(BaseModel):
    title = models.CharField(verbose_name=_('Title'), max_length=200)
    slug = models.SlugField(verbose_name=_('Slug'), unique=True, max_length=200)
    content = RichTextUploadingField(verbose_name=_('Content'), )
    topic = models.ForeignKey('blog.Topic', verbose_name=_('Topic'), related_name='articles',
                              on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField('blog.Tag', verbose_name=_('Tags'), related_name='articles', blank=True)
    image = models.ImageField(verbose_name=_('Image'), upload_to='blog/article_images/', blank=True, null=True)
    is_published = models.BooleanField(_('Is published'), default=True)
    view_count = models.PositiveIntegerField(verbose_name=_('View count'), default=0)
    popularity_score = models.FloatField(verbose_name=_('Popularity Score'), default=0.0)
    series = models.ForeignKey('ArticleSeries', verbose_name=_('Series'), related_name='articles', on_delete=models.SET_NULL, null=True, blank=True)
    series_sequence_number = models.PositiveIntegerField(verbose_name=_('Series sequence number'), null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.series and self.series_sequence_number is None:
            self.series_sequence_number = self.series.get_next_sequence_number()

        self.slug = generate_slug_from_title(self)
        super().save(*args, **kwargs)

    def increment_view_count(self, request):
        client_ip = request.META.get('REMOTE_ADDR')
        user_id = request.user.id if request.user.is_authenticated else None
        cache_key = f'article_view_{self.id}_{user_id or client_ip}'

        if not cache.get(cache_key):
            self.view_count = models.F('view_count') + 1
            self.save(update_fields=['view_count'])
            cache.set(cache_key, True, 60 * 60 * 24)

    def calculate_popularity_score(self):
        now = timezone.now()

        time_weight = 0.3
        view_weight = 0.4
        interaction_weight = 0.3

        time_diff = now - self.created_at
        time_factor = 1 / (1 + time_diff.days)

        view_factor = min(self.view_count / 1000, 1)

        like_count = self.interactions.filter(interaction_type=InteractionType.LIKE).count()
        comment_count = self.comments.count()
        interaction_factor = min((like_count + comment_count) / 100, 1)

        score = (
                time_weight * time_factor +
                view_weight * view_factor +
                interaction_weight * interaction_factor
        )

        self.popularity_score = score
        self.save(update_fields=['popularity_score'])

        return score

    class Meta:
        ordering = ['-created_at']
        verbose_name = _('Article')
        verbose_name_plural = _('Articles')
        constraints = (
            UniqueConstraint(fields=['title', 'creator', ], name='unique_title_creator'),
            UniqueConstraint(fields=['series', 'series_sequence_number', ], name='unique_series_sequence_number'),
        )

    @property
    def likes(self):
        return self.interactions.filter(interaction_type=InteractionType.LIKE)

    @property
    def dislikes(self):
        return self.interactions.filter(interaction_type=InteractionType.DISLIKE)

    @property
    def is_featured(self):
        return hasattr(self, 'featured')

    def user_has_liked(self, user: Union[User, None]) -> bool:
        if user is None or user.is_anonymous:
            return False
        return self.interactions.filter(creator=user, interaction_type='like').exists()

    def user_has_disliked(self, user: Union[User, None]) -> bool:
        if user is None or user.is_anonymous:
            return False
        return self.interactions.filter(creator=user, interaction_type='dislike').exists()

    # ... existing fields ...

    def safe_excerpt(self, words=30, char_limit=None):
        plain_text = strip_tags(self.content)

        if char_limit:
            return Truncator(plain_text).chars(char_limit, truncate='...')
        else:
            return Truncator(plain_text).words(words, truncate='...')

    def swap_sequence_with(self, other_article: 'Article') -> Tuple['Article', 'Article']:
        if not self.series:
            raise ValueError("This article does not belong to a series.")
        return self.series.swap_article_sequence_numbers(self, other_article)


class Topic(BaseModel):
    name = models.CharField(verbose_name=_('Name'), max_length=100, unique=True)
    slug = models.SlugField(verbose_name=_('Slug'), unique=True, max_length=100)
    description = models.TextField(verbose_name=_('Description'), blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = _('Topic')
        verbose_name_plural = _('Topics')

    def __str__(self):
        return self.name


class Comment(BaseModel):
    article = models.ForeignKey(Article, verbose_name=_('Article'), related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(verbose_name=_('Content'), )
    is_approved = models.BooleanField(_('Is approved'), default=True)

    def __str__(self):
        return f'Comment by {self.creator} on {self.article.title}'

    class Meta:
        ordering = ['-created_at']
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')


class Tag(BaseModel):
    name = models.CharField(verbose_name=_('Name'), max_length=100, unique=True)
    slug = models.SlugField(verbose_name=_('Slug'), unique=True, max_length=100)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ['name']
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')


class FeaturedArticle(BaseModel):
    class FeaturedReason(models.TextChoices):
        EDITOR_CHOICE = 'editor_choice', _("Editor's Choice")
        STAFF_PICK = 'staff_pick', _("Staff Pick")
        TOPIC_HIGHLIGHT = 'topic_highlight', _("Topic Highlight")
        POPULAR_ARTICLE = 'popular_article', _("Popular Article")

    article = models.OneToOneField('Article', verbose_name=_('Article'), on_delete=models.CASCADE,
                                   related_name='featured')
    featured_reason = models.TextField(blank=True, choices=FeaturedReason.choices,
                                       verbose_name=_('Reason for Featuring'))

    def __str__(self):
        return f'Featured article {self.article.title}'

    class Meta:
        verbose_name = _('Featured Article')
        verbose_name_plural = _('Featured Articles')
        ordering = ['-created_at']


class ArticleInteraction(BaseModel):
    article = models.ForeignKey('Article', verbose_name=_('Article'), on_delete=models.CASCADE,
                                related_name='interactions')
    interaction_type = models.CharField(choices=InteractionType.choices, max_length=10)

    def __str__(self):
        return f'Interaction {self.creator.username} {self.interaction_type} {self.article.title}'

    class Meta:
        verbose_name = _('Interaction')
        verbose_name_plural = _('Interactions')
        ordering = ['-created_at']


class ArticleSeries(BaseModel):
    title = models.CharField(verbose_name=_('Title'), max_length=200)
    slug = models.SlugField(verbose_name=_('Slug'), unique=True)
    description = models.TextField(verbose_name=_('Description'), blank=True, default='')

    def __str__(self):
        return f'{self.title}'

    def save(self, *args, **kwargs):
        self.slug = generate_slug_from_title(self)
        super().save(*args, **kwargs)

    @transaction.atomic
    def swap_article_sequence_numbers(self, article_1: 'Article', article_2: 'Article'):
        # TODO Fix the bug with unique together
        if article_1.series != article_2.series:
            raise ValueError("Both articles must belong to this series.")

        article_1.series_sequence_number, article_2.series_sequence_number = article_2.series_sequence_number, article_1.series_sequence_number
        Article.objects.bulk_update([article_1, article_2], ["series_sequence_number"])

        return article_1.refresh_from_db(), article_2.refresh_from_db()

    def get_next_sequence_number(self) -> int:
        max_sequence = self.articles.aggregate(max_seq=models.Max('series_sequence_number'))['max_seq']
        return (max_sequence or 0) + 1

    class Meta:
        verbose_name = _('Article Series')
        verbose_name_plural = _('Article Series')

blog/models/post.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from content.models import BaseModel


class Post(BaseModel):
    title = models.CharField(verbose_name=_('Title'), max_length=200)
    slug = models.SlugField(verbose_name=_('Slug'), unique=True)
    content = models.TextField(verbose_name=_('Content'), )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']

blog/forms.py
from django import forms

from blog.models import Article


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'series', 'series_sequence_number', 'content', 'topic', 'tags', 'image')

blog/templates/blog/partials/article_card.html
{% load static %}

<div id="article{{ article.pk }}" class="p-6 flex flex-col justify-between min-h-96 space-y-3 bg-skin-surface rounded-sm md:rounded-md shadow-md overflow-hidden transition-all duration-300 hover:bg-skin-surface-hover col-span-12 md:col-span-6 xxl:col-span-4
">
    <div class="flex justify-between">
        <span class="text-xs text-skin-muted">{{ article.created_at|date:"F d, Y" }}</span>
        {% if article.featured %}
            <span class="text-sm text-skin-accent">{{ article.featured.get_featured_reason_display }}</span>
        {% endif %}
    </div>
    <h2 class="text-4xl font-serif font-bold text-skin-base">{{ article.title }}</h2>

    <div class="flex flex-wrap gap-1">
        {% if article.topic %}
            {% include 'blog/partials/topic_chip.html' with topic=article.topic %}
        {% endif %}
        {% for tag in article.tags.all %}
            {% include 'blog/partials/tag_chip.html' with tag=tag %}
        {% endfor %}
    </div>
    <p class="text-skin-muted mb-4">{{ article.safe_excerpt }}</p>
    <div class="flex items-center justify-between">
        <div class="flex flex-wrap items-center gap-4 text-sm text-skin-muted">
            <span>
                <c-icons.eye/>
                <span>{{ article.view_count }}</span>
            </span>
            <span class="flex items-center">
                <c-icons.thumbs-up/>
                <span>{{ article.likes.count }}</span>
            </span>
            <span>
                <c-icons.thumbs-down/>
                <span>{{ article.dislikes.count }}</span>
            </span>
            <span>
                <c-icons.message-square/>
                <span>{{ article.comments.count }}</span>
            </span>
        </div>

        <a href="{% url 'blog:article_detail' slug=article.slug %}"
           class="text-skin-link hover:text-skin-link font-semibold">
            Read More
        </a>

    </div>
</div>

blog/templates/blog/partials/article_form.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <c-input :field="form.title"></c-input>
    <c-select :field="form.series"></c-select>
    <c-input :field="form.series_sequence_number"></c-input>
    {{ form.content }}
    
    <c-select :field="form.topic"></c-select>
    <c-select :field="form.tags"></c-select>
    <c-input :field="image"></c-input>
    
    <c-button type="submit">Create</c-button>
</form>

blog/templates/blog/partials/article_list.html
{% for article in articles %}
    {% include 'blog/partials/article_card.html' %}
{% endfor %}

blog/templates/blog/partials/article_list_item.html
{% load static %}
<div class="p-4 shadow-md rounded-md bg-skin-base">
    <div class="flex-grow">
        <h3 class="text-lg font-semibold text-skin-link mb-1">
            <a href="{% url 'blog:article_detail' slug=article.slug %}"
               class="hover:text-skin-link-inverted transition-colors duration-200">
                {{ article.title }}
            </a>
        </h3>
        <div class="flex flex-wrap items-center text-sm text-skin-muted gap-2 mb-2">
            <c-blog.badge>{{ article.topic.name }}</c-blog.badge>
            <span>by {{ article.creator.username }}</span>
            <span>{{ article.created_at|date:"M d, Y" }}</span>
        </div>
        <div class="flex flex-wrap items-center gap-4 text-sm text-skin-muted">
            <span>
                <c-icons.eye/>
                <span>{{ article.view_count }}</span>
            </span>
            <span class="flex items-center">
                <c-icons.thumbs-up/>
                <span>{{ article.likes.count }}</span>
            </span>
            <span>
                <c-icons.thumbs-down/>
                <span>{{ article.dislikes.count }}</span>
            </span>
            <span>
                <c-icons.message-square/>
                <span>{{ article.comments.count }}</span>
            </span>
            <span>
                <c-icons.trending-up/>
                <span>{{ article.popularity_score }}</span>
            </span>
        </div>
    </div>
</div>

blog/templates/blog/partials/article_series_list.html
<ol>
{% for article in series.articles.all %}
    <li><c-link href="{% url 'blog:article_detail' slug=article.slug %}">{{ forloop.counter }}. {{ article.title }}</c-link></li>
{% endfor %}
</ol>

blog/templates/blog/partials/comment_list.html
{% load static %}

<div class="max-w-3xl mx-auto px-4 py-8">

  <!-- Comment Section -->
  <section class="mt-12">
    <h2 class="text-2xl font-bold text-skin-base mb-4">Comments</h2>
    <div class="space-y-6">

      {% for comment in article.comments.all %}
    {% include 'blog/partials/comment_list_item.html' %}
      {% empty %}
        <p class="text-skin-muted">No comments yet. Be the first to comment!</p>
      {% endfor %}
    </div>

    {% if request.user.is_authenticated %}
      <form method="post" action="{% url 'blog:article_add_comment' slug=article.slug %}" class="mt-8">
        {% csrf_token %}
        <div class="flex items-start space-x-4">
          {% if request.user.profile_image %}
            <img src="{{ request.user.profile_image.url }}" alt="{{ request.user.username }}" class="w-10 h-10 rounded-full">
          {% else %}
            <div class="w-10 h-10 rounded-full bg-gray-300"></div>
          {% endif %}
          <div class="min-w-0 flex-1">
            <div class="border-b border-gray-200 focus-within:border-skin-primary">
              <textarea
                rows="3"
                name="content"
                id="comment"
                class="block w-full resize-none border-0 bg-skin-muted border-b border-transparent p-0 pb-2 text-skin-base placeholder:text-skin-muted focus:border-purple-600 focus:ring-0 sm:text-sm sm:leading-6"
                placeholder="Add a comment..."
              ></textarea>
            </div>
          </div>
        </div>
        <div class="mt-2 flex justify-end">
          <button
            type="submit"
            class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-skin-base bg-skin-primary hover:bg-skin-primary-hover focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500"
          >
            <c-icons.send/>
            Post
          </button>
        </div>
      </form>
    {% else %}
      <p class="mt-8 text-skin-base">Please <a href="{% url 'login' %}" class="text-skin-link hover:text-skin-link-active">log in</a> to add a comment.</p>
    {% endif %}
  </section>
</div>

blog/templates/blog/partials/comment_list_item.html
<div class="bg-gray-50 p-4 rounded-lg">
    <div class="flex justify-between items-start mb-2">
        <span class="font-semibold text-gray-700">{{ comment.creator.username }}</span>
        <span class="text-sm text-skin-muted">
              {{ comment.created_at|date:"F d, Y" }}
            </span>
    </div>
    <p class="text-skin-muted">{{ comment.content }}</p>
</div>

blog/templates/blog/partials/featured_article_list.html
{% for featured_article in featured_articles %}
    {% include 'blog/partials/featured_article_list_item.html' %}
{% endfor %}

blog/templates/blog/partials/featured_article_list_item.html
{{ featured_article.article.title }}

blog/templates/blog/partials/like_dislike_buttons.html
<div id="interaction-buttons-{{ article.pk }}" class="flex items-center space-x-4 mt-4">
    <button hx-post="{% url 'blog:toggle_like' slug=article.slug %}"
            hx-target="#interaction-buttons-{{ article.pk }}"
            hx-swap="outerHTML"
            class="flex items-center space-x-1 transition-all duration-300 ease-in-out {% if article.user_has_liked %}text-blue-500{% else %}text-skin-muted{% endif %} hover:text-blue-600">
        <c-icons.heart
                class="h-6 w-6 transition-transform duration-300 ease-in-out {% if article.user_has_liked %}scale-110{% endif %}"
                fill="{% if article.user_has_liked %}{% else %}none{% endif %}"/>
        <span id="like-count-{{ article.pk }}" class="font-semibold">{{ article.likes.count }}</span>
    </button>
    <button hx-post="{% url 'blog:toggle_dislike' slug=article.slug %}"
            hx-target="#interaction-buttons-{{ article.pk }}"
            hx-swap="outerHTML"
            class="flex items-center space-x-1 transition-all duration-300 ease-in-out {% if article.user_has_disliked %}text-red-500{% else %}text-skin-muted{% endif %} hover:text-red-600">
        <c-icons.thumbs-down
                class="h-6 w-6 transition-transform duration-300 ease-in-out {% if article.user_has_disliked %}scale-110{% endif %}"
                fill="{% if article.user_has_disliked %}{% else %}none{% endif %}"/>
        <span id="dislike-count-{{ article.pk }}" class="font-semibold">{{ article.dislikes.count }}</span>
    </button>
</div>

blog/templates/blog/partials/tag_chip.html
<a href="{% url 'blog:tag_detail' slug=tag.slug %}">
    <span class="bg-skin-tertiary hover:bg-skin-surface-hover py-1 px-3 text-sm rounded-full border shadow">{{ tag.name }}</span>
</a>

blog/templates/blog/partials/topic_chip.html
<a href="{% url 'blog:topic_detail' slug=topic.slug %}">
    <span class="bg-skin-secondary hover:bg-bg-skin-surface-hover text-skin-base py-1 px-3 text-sm border shadow-sm transition-all">{{ topic.name }}</span>
</a>