blog/urls.py
from django.urls import path
from django.urls.conf import include

from blog.views import article_list_view, article_detail_view, home_view, article_create_view, tag_list_view, \
    tag_detail_view, tag_create_view, tag_edit_view, tag_delete_view, topic_list_view, topic_create_view, \
    topic_detail_view, topic_edit_view, topic_delete_view, article_like_count_view, article_dislike_count_view, \
    toggle_dislike_view, toggle_like_view, article_archive_view, article_edit_view, article_view_count_view, \
    article_comments_view, article_add_comment_view, article_series_list_view, \
    article_series_detail_view, article_series_get_next_sequence_number_view

app_name = 'blog'

urlpatterns = [
    path('', home_view, name='index'),
    path('articles/', include([
        path('', article_list_view, name='article_list'),
        path('create', article_create_view, name='article_create'),
        path('<str:slug>/',
             include([
                 path('', article_detail_view, name='article_detail'),
                 path('edit', article_edit_view, name='article_edit'),
                 path('archive', article_archive_view, name='article_archive'),
                 path('like_count', article_like_count_view, name='article_like_count'),
                 path('dislike_count', article_dislike_count_view, name='article_dislike_count'),
                 path('toggle_like/', toggle_like_view, name='toggle_like'),
                 path('toggle_dislike/', toggle_dislike_view, name='toggle_dislike'),
                 path('view_count/', article_view_count_view, name='article_view_count'),
                 path('comments', article_comments_view, name='article_comments'),
                 path('add_comment', article_add_comment_view, name='article_add_comment')

             ])
             ),
        path('article_series/', include([
            path('', article_series_list_view, name='article_series_list'),
            path('<str:slug>/', include([
                path('', article_series_detail_view, name='article_series_detail'),
                path('get_next_sequence_number', article_series_get_next_sequence_number_view,
                     name='article_series_get_next_sequence_number')
            ]))
        ])),
        path('tags/', include([
            path('', tag_list_view, name='tag_list'),
            path('create', tag_create_view, name='tag_create'),
            path('<str:slug>/', include([
                path('', tag_detail_view, name='tag_detail'),
                path('edit', tag_edit_view, name='tag_edit'),
                path('delete', tag_delete_view, name='tag_delete'),
            ]))
        ])),
        path('topics/', include([
            path('', topic_list_view, name='topic_list'),
            path('create', topic_create_view, name='topic_create'),
            path('<str:slug>/', include([
                path('', topic_detail_view, name='topic_detail'),
                path('edit', topic_edit_view, name='topic_edit'),
                path('delete', topic_delete_view, name='topic_delete'),
            ]))
        ]))
    ]))
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('content.urls', namespace='content')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('arcus/', include('arcus.urls', namespace='arcus')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('users/', include('django.contrib.auth.urls', )),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'schir.dev admin'

tools/urls.py
from django.urls import path

from tools import views
from tools.views import theme_view, css_display_cheatsheet_view

app_name = 'tools'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('retirement_calculator', views.retirement_calculator_view, name='retirement_calculator'),
    path('css_display_cheatsheet', css_display_cheatsheet_view, name='css_display_cheatsheet'),
    path('theme', theme_view, name='theme'),
]

tools/models.py
from django.db import models

# Create your models here.

tools/forms.py
from django import forms
from django.utils import timezone


class RetirementCalculatorForm(forms.Form):
    INFLATION_GROWTH_STRATEGY_CHOICES = [
        ('fixed', 'Fixed'),
        ('percentage_increase', 'Percentage Increase'),
    ]
    EXPENSE_GROWTH_STRATEGY_CHOICES = [
        ('fixed', 'Fixed'),
        ('percent_of_income', 'Percentage of Income'),
    ]

    INCOME_GROWTH_STRATEGY_CHOICES = [
        ('fixed', 'Fixed'),
        ('percentage_increase', 'Percentage Increase'),
    ]

    INCOME_TAX_STRATEGY_CHOICES = [
        ('simple', 'Simple'),
        ('bracket', 'Bracket'),
    ]

    FILING_STATUS_CHOICES = [
        ('single', 'Single'),
        ('married_joint', 'Married Filing Jointly'),
        ('married_separate', 'Married Filing Separately'),
        ('head_household', 'Head of Household'),
    ]

    BANK_CONTRIBUTION_STRATEGY_CHOICES = [
        ('fixed', 'Fixed'),
        ('percent_of_income', 'Percent of Income'),
    ]

    TAX_DEFERRED_CONTRIBUTION_STRATEGY_CHOICES = [
        ('fixed', 'Fixed Contribution'),
        ('percent_of_income', 'Percentage of Income'),
        ('until_company_match', 'Until Employer Match Met'),
        ('max', 'Max Out'),
    ]

    TAXABLE_CONTRIBUTION_STRATEGY_CHOICES = [
        ('fixed', 'Fixed Contribution'),
        ('percent_of_income', 'Percentage of Income'),
    ]

    IRA_CONTRIBUTION_STRATEGY_CHOICES = [
        ('fixed', 'Fixed Contribution'),
        ('percent_of_income', 'Percentage of Income'),
        ('max', 'Max Out')
    ]

    EMPLOYER_CONTRIBUTION_STRATEGY_CHOICES = [
        ('none', 'Does not contribute'),
        ('percentage_of_contribution', 'Match Percentage of Contribution'),
        ('percentage_of_compensation', 'Percentage of Compensation'),
        ('fixed', 'Fixed Amount'),
    ]

    EXPENSES_GROWTH_STRATEGY_CHOICES = [
        ('fixed', 'Fixed'),
        ('percentage_increase', 'Percentage Increase'),
    ]

    WITHDRAWAL_STRATEGY_CHOICES = [
        ('sequential', 'Sequential'),
        ('proportional', 'Proportional'),
        ('tax_bracket_management', 'Tax Bracket Management'),
        ('roth_conversion_ladder', 'Roth Conversion Ladder'),
        ('bridging', 'Bridging'),

    ]

    RETIREMENT_STRATEGY_CHOICES = [
        ('age', 'Retire at a Specific Age'),
        ('percent_rule', 'Retire When the % Rule Is Met'),
        ('target_savings', 'Retire When a Target Savings Amount Is Reached'),
        ('debt_free', 'Retire When Debt Is Eliminated'),
    ]

    CASH_MAINTENANCE_STRATEGY_CHOICES = [
        ('fixed', 'Fixed Cash Maintenance'),
        ('variable_cash_reserve', 'Variable Cash Reserve'),
        ('percentage_of_portfolio', 'Percentage of Portfolio'),
    ]

    age = forms.IntegerField(
        min_value=0,
        max_value=100,
        initial=30,
        label="Age",
        help_text="Your current age in years.",
    )

    retirement_strategy = forms.ChoiceField(
        choices=RETIREMENT_STRATEGY_CHOICES,
        initial='age',
        label='Retirement Strategy',
        help_text='Select the strategy that dictates when you plan to retire and stop investing.',
    )

    retirement_expenses = forms.FloatField(
        min_value=0,
        label='Annual Retirement Expenses',
        help_text='Your expected annual expenses during retirement.',
    )

    retirement_savings_amount = forms.FloatField(
        min_value=0,
        label='Target Savings Amount',
        help_text='The total savings amount you aim to reach before retiring.',
    )

    retirement_withdrawal_rate = forms.FloatField(
        min_value=0,
        initial=4.0,
        label='Retirement Rate of Withdrawal',
        help_text='Enter the percentage of your retirement savings you plan to withdraw annually (e.g., 4 for 4%).'
    )

    year = forms.IntegerField(
        min_value=0,
        max_value=100,
        initial=timezone.now().year,
        label="Year",
        help_text="Starting Year",
    )

    retirement_age = forms.IntegerField(
        min_value=0,
        max_value=100,
        initial=65,
        label="Retirement Age",
        help_text="The age at which you plan to retire.",
    )

    life_expectancy = forms.IntegerField(
        min_value=0,
        max_value=100,
        initial=85,
        label="Life Expectancy",
        help_text="Your estimated life expectancy in years.",
    )

    tax_deferred_savings = forms.IntegerField(
        min_value=0,
        initial=100000,
        label="Tax-Deferred Savings",
        help_text="Your current savings in tax-deferred accounts (e.g., 401(k), Traditional IRA).",
    )

    tax_deferred_growth_rate = forms.FloatField(
        min_value=0,
        initial=6.0,
        label="Tax-Deferred Growth Rate (%)",
        help_text="Expected annual growth rate for tax-deferred savings as a percentage.",
    )

    taxable_savings = forms.IntegerField(
        min_value=0,
        initial=50000,
        label="Taxable Savings",
        help_text="Your current savings in taxable accounts.",
    )

    ira_savings = forms.IntegerField(
        min_value=0,
        initial=30000,
        label="Tax-Exempt Savings",
        help_text="Your current savings in tax-exempt accounts (e.g., Roth IRA).",
    )

    cash = forms.IntegerField(
        min_value=0,
        initial=20000,
        label="Cash",
        help_text="Your current bank savings (e.g., checking, savings accounts).",
    )

    cash_maintenance_strategy = forms.ChoiceField(
        choices=CASH_MAINTENANCE_STRATEGY_CHOICES,
        initial='fixed',
        label="Cash Maintenance Strategy",
        help_text="Strategies for maintaining cash.",
    )

    cash_maintenance_target_amount = forms.IntegerField(
        min_value=0,
        initial=0,
        label="Cash Maintenance Target Amount",
    )

    cash_maintenance_months_of_expenses_in_reserve= forms.IntegerField(
        min_value=0,
        initial=6,
        label="Cash Maintenance Number of Month Expenses",
    )

    annual_taxable_contribution = forms.IntegerField(
        min_value=0,
        initial=500,
        label="Annual Taxable Contribution",
        help_text="Your annual contribution to taxable savings accounts.",
    )

    tax_deferred_contribution_fixed_amount = forms.IntegerField(
        min_value=0,
        initial=1000,
        label="Annual Tax-Deferred Contribution",
        help_text="Your annual contribution to tax-deferred accounts.",
    )

    tax_deferred_contribution_percentage = forms.FloatField(
        min_value=0,
        max_value=100,
        initial=5.0,
        label="Tax-Deferred Contribution Percentage",
        help_text="The percentage of your pre-tax income to contribute to tax-deferred accounts.",
    )

    ira_contribution_percentage = forms.FloatField(
        min_value=0,
        max_value=100,
        initial=5.0,
        label="Tax-Exempt Contribution Percentage",
        help_text="The percentage of your pre-tax income to contribute to tax-exempt accounts (e.g., Roth IRA).",
    )

    taxable_contribution_percentage = forms.FloatField(
        min_value=0,
        max_value=100,
        initial=5.0,
        label="Taxable Contribution Percentage",
        help_text="The percentage of your pre-tax income to contribute to taxable accounts.",
    )

    employer_match_percentage_limit = forms.FloatField(
        min_value=0,
        max_value=100,
        initial=3.0,
        label="Employer Match Percentage Limit (%)",
        help_text="The maximum percentage of your compensation that your employer will match.",
    )

    employer_match_percentage = forms.FloatField(
        min_value=0,
        max_value=100,
        initial=100.0,
        label="Employer Match Percentage (%)",
        help_text="The percentage of your contribution that your employer will match.",
    )

    ira_contribution_fixed_amount = forms.IntegerField(
        min_value=0,
        initial=500,
        label="Annual Tax-Exempt Contribution",
        help_text="Your annual contribution to tax-exempt accounts (e.g., Roth IRA).",
    )

    expenses = forms.IntegerField(
        min_value=0,
        initial=40000,
        label="Annual Expenses",
        help_text="Your estimated annual living expenses.",
    )

    inflation_rate = forms.FloatField(
        min_value=0,
        initial=2.0,
        label="Inflation Rate (%)",
        help_text="Expected annual inflation rate as a percentage.",
    )

    taxable_savings_growth_rate = forms.FloatField(
        min_value=0,
        initial=6.0,
        label="Taxable Savings Growth Rate (%)",
        help_text="Expected annual growth rate for taxable savings as a percentage.",
    )

    ira_growth_rate = forms.FloatField(
        min_value=0,
        initial=6.0,
        label="IRA Growth Rate (%)",
        help_text="Expected annual growth rate for IRA savings as a percentage.",
    )

    income_pre_taxed = forms.IntegerField(
        min_value=0,
        initial=60000,
        label="Annual Pre-Tax Income",
        help_text="Your current annual income before taxes.",
    )

    target_annual_retirement_spending_pre_taxed = forms.IntegerField(
        min_value=0,
        initial=50000,
        label="Target Annual Retirement Spending (Pre-Tax)",
        help_text="Your target annual spending in retirement, before taxes.",
    )

    target_end_of_life_savings_pre_taxed = forms.IntegerField(
        min_value=0,
        initial=100000,
        label="Target End-of-Life Savings (Pre-Tax)",
        help_text="The amount you aim to have saved at the end of your life, before taxes.",
    )

    inflation_strategy = forms.ChoiceField(
        choices=INFLATION_GROWTH_STRATEGY_CHOICES,
        initial='fixed',
        label="Inflation Growth Strategy"
    )

    income_growth_strategy = forms.ChoiceField(
        choices=INCOME_GROWTH_STRATEGY_CHOICES,
        initial='fixed',
        label="Income Growth Strategy"
    )

    taxable_contribution_strategy = forms.ChoiceField(

tools/views.py
from django.contrib.auth.decorators import login_not_required
from django.shortcuts import render

from tools.forms import RetirementCalculatorForm


# Create your views here.
@login_not_required
def index_view(request):
    return render(request, template_name='tools/index.html')


@login_not_required
def retirement_calculator_view(request):
    form = RetirementCalculatorForm()
    context = {'form': form}
    return render(request, template_name='tools/retirement_calculator.html', context=context)


@login_not_required
def theme_view(request):
    template_name = 'tools/theme.html'
    colors = ['base', 'muted', 'primary', 'secondary', 'tertiary', 'accent', 'error', 'success', 'link', 'link-hover', 'link-active',
              'info', 'warning']
    themes = ['light', 'dark']
    context = {'themes': themes, 'colors': colors}
    return render(request, template_name=template_name, context=context)


@login_not_required
def css_display_cheatsheet_view(request):
    template_name = 'tools/css_display_cheatsheet.html'
    context = dict()
    return render(request, template_name=template_name, context=context)

tools/templates/tools/_template.html
{% extends 'tools/base.html' %}
{% block head_title %}{% endblock %}
{% block content %}
	
{% endblock %}

tools/templates/tools/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
    <title>{% block head_title %}Arcus{% endblock %}</title>
    <link rel="icon" href="{% static 'content/img/logos/logo.gif' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    {% tailwind_css %}

    {% block head %}{% endblock %}
    {% block styles %}{% endblock %}

    <script src="{% static 'js/htmx.min.js' %}"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/persist@3.x.x/dist/cdn.min.js"></script>
    <script src="//unpkg.com/alpinejs" defer></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
</head>

<body
        class="bg-skin-primary text-lg text-skin-base"
        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
        :data-theme="theme"
        x-data="{ theme : $persist('light'), toggleTheme() { this.theme = this.theme === 'dark' ? 'light' : 'dark' }, 
           expandSidebar: $persist(true),}">
<c-navbar></c-navbar>
<c-sidenav>
    <li class="mb-4" :class="expandSidebar ? 'ml-2' : 'ml-0'">
        <c-arcus.link href="{% url 'tools:retirement_calculator' %}" class="flex items-center">
            <c-icons.trending-up class="inline-block mr-2"/>
            <span x-show="expandSidebar">Retirement Calculator</span>
        </c-arcus.link>
    </li>
    <li class="mb-4" :class="expandSidebar ? 'ml-2' : 'ml-0'">
        <c-arcus.link href="{% url 'tools:theme' %}" class="flex items-center">
            <c-icons.sun class="inline-block mr-2"/>
            <span x-show="expandSidebar">Theme</span>
        </c-arcus.link>
    </li>
    <li class="mb-4" :class="expandSidebar ? 'ml-2' : 'ml-0'">
        <c-arcus.link href="{% url 'tools:css_display_cheatsheet' %}" class="flex items-center">
            <c-icons.code class="inline-block mr-2"/>
            <span x-show="expandSidebar">CSS Display Cheatsheet</span>
        </c-arcus.link>
    </li>
</c-sidenav>
<div class="flex flex-col md:flex-row min-h-nav-offset mx-auto">

    <!-- Main Content -->
    <main class="px-4 py-8 mx-auto" x-transition :class="expandSidebar ? 'ps-64' : 'ps-16'">
        {% block before_content %}{% endblock %}
        <main class="flex-grow container p-16 bg-skin-surface shadow-md rounded-md space-y-12">
            {% block content %}{% endblock %}
        </main>
    </main>
</div>

{% block javascript %}{% endblock %}

<script>
    (function () {

        document.addEventListener('DOMContentLoaded', function () {
            const navbarHeight = document.querySelector('nav').offsetHeight;

            // Adjust scrolling to each anchor section
            document.querySelectorAll('a[href^=\"#\"]').forEach(anchor => {
                anchor.addEventListener('click', function (e) {
                    e.preventDefault();

                    const targetId = this.getAttribute('href').substring(1);
                    const targetElement = document.getElementById(targetId);

                    if (targetElement) {
                        window.scrollTo({
                            top: targetElement.offsetTop - navbarHeight, // Adjust by navbar height
                            behavior: 'smooth'
                        });
                    }
                });
            });
        });

        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    })();
</script>
</body>
</html>

tools/templates/tools/index.html
{% extends 'tools/base.html' %}
{% block head_title %}Tools{% endblock %}
{% block content %}
    <h1 class="text-4xl font-bold font-serif">Tools</h1>
    <div class="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4 xl:gap-8">
        <c-card>
            <c-slot name="title">Retirement Calculator</c-slot>
            <c-slot name="content">
                <p class="italic text-skin-muted">
                    Take control of your retirement goals with our comprehensive calculator. This tool lets you model various retirement
                    strategies, explore income growth paths, and assess expenses. It's designed to help you understand how contributions,
                    tax strategies, and investments can bring you closer to financial independence.
                </p>
            </c-slot>
            <c-slot name="actions">
                <c-link href="{% url 'tools:retirement_calculator' %}">Try it Out</c-link>
            </c-slot>
        </c-card>
        <c-card>
            <c-slot name="title">CSS Display Properties Cheatsheet</c-slot>
            <c-slot name="content">
                <p class="italic text-skin-muted">
                    Quickly navigate the essentials of CSS display properties. This guide is built to help you understand, compare, and
                    effectively use different display types across HTML elements. Each row provides insights into layout behaviors and
                    common applications, offering a clear reference whether you’re learning or fine-tuning your design skills.
                </p>
            </c-slot>
            <c-slot name="actions">
                <c-link href="{% url 'tools:retirement_calculator' %}">Explore the Cheatsheet</c-link>
            </c-slot>
        </c-card>
        <c-card>
            <c-slot name="title">Theme Behind the Design</c-slot>
            <c-slot name="content">
                <p class="italic text-skin-muted">
                    Explore the visual elements and color palette that drive the aesthetic and functionality of this site. This theme has
                    been crafted to balance clarity and creativity, aiming to make navigation intuitive and visually appealing. Below,
                    you'll see how different components work together to create a cohesive, accessible, and professional experience.
                </p>
            </c-slot>
            <c-slot name="actions">
                <c-link href="{% url 'tools:retirement_calculator' %}">View Full Theme</c-link>
            </c-slot>
        </c-card>
    </div>

{% endblock %}

tools/templates/tools/theme.html
{% extends 'tools/base.html' %}
{% block content %}
    <div class="bg-skin-surface space-y-8">
        <h1 class="text-3xl font-bold">Theme Color Palette</h1>
        {% for theme in themes %}
            <div class="bg-skin-base p-8 shadow-lg rounded-2xl" data-theme="{{ theme }}">
                <h2 class="text-2x font-bold mb-4 text-skin-base">{{ theme|title }} Theme</h2>
                <div class="p-8 bg-skin-surface rounded-md shadow-lg space-y-16">
                    <div class="grid grid-cols-[repeat(14,minmax(0,1fr))] gap-4">
                        <div class="space-y-4">
                            <div class="h-8"><h1 class="text-xl text-skin-base font-medium capitalize"></h1></div>
                            <div class="h-16"><h1 class="text-xl text-skin-base font-medium capitalize">Shadow</h1></div>
                            <div class="h-16"><h1 class="text-xl text-skin-base font-medium capitalize">Border</h1></div>
                            <div class="h-16"><h1 class="text-xl text-skin-base font-medium capitalize">Ring</h1></div>
                            <div class="h-16"><h1 class="text-xl text-skin-base font-medium capitalize">BorderRing</h1></div>
                        </div>
                        {% for color in colors %}
                            <div class="space-y-4">
                                <div>
                                    <div class="text-skin-{{ color }} font-medium capitalize">{{ color }}</div>
                                    <div class="text-sm text-skin-base text-skin-{{ color }}"></div>
                                </div>
                                <div class="p-4 h-16 bg-skin-{{ color }} shadow shadow-md rounded-md">
                                    <h1 class="self-center text-xl text-skin-{{ color }} font-medium capitalize">Aa</h1>
                                </div>
                                <div class="p-4 h-16 bg-skin-{{ color }} border border-skin-{{ color }} rounded-md">
                                    <h1 class="text-xl text-skin-{{ color }} font-medium capitalize">Aa</h1>
                                </div>
                                <div class="p-4 h-16 bg-skin-{{ color }} ring-2 ring-skin-{{ color }} rounded-md">
                                    <h1 class="text-xl text-skin-{{ color }} font-medium capitalize">Aa</h1>
                                </div>
                                <div class="p-4 h-16 bg-skin-{{ color }} border border-skin-{{ color }} ring-2 ring-skin-{{ color }} rounded-md">
                                    <h1 class="text-xl text-skin-{{ color }} font-medium capitalize">Aa</h1>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    <article class="prose prose-skin">
                        <h1>Article Title</h1>
                        <p>This is the body text where the main content of the article will be. It uses the defined pink body color.</p>

                        <h2>Subheading</h2>
                        <p>Here’s a lead paragraph to introduce a section. The lead text should be visually distinct.</p>

                        <h3>Another Subheading</h3>
                        <p>More content follows here, potentially with <strong>bold</strong> text and <em>italic</em> text for emphasis.</p>

                        <a href="#">This is a link styled with the pink theme.</a>

                        <blockquote>
                            <p>This is a quote from an external source, styled with borders and a distinct color.</p>
                        </blockquote>

                        <p>Lists can be styled as well:</p>
                        <ul>
                            <li>First bullet item</li>
                            <li>Second bullet item</li>
                            <li>Third bullet item</li>
                        </ul>

                        <p>Code blocks are formatted with different colors:</p>
                        <pre><code>console.log('Hello, World!');</code></pre>

                        <p>Here’s a horizontal rule separating content:</p>
                        <hr>

                        <p>Tables can also be incorporated:</p>
                        <table>
                            <thead>
                            <tr>
                                <th>Header 1</th>
                                <th>Header 2</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Row 1, Col 1</td>
                                <td>Row 1, Col 2</td>
                            </tr>
                            <tr>
                                <td>Row 2, Col 1</td>
                                <td>Row 2, Col 2</td>
                            </tr>
                            </tbody>
                        </table>
                    </article>
                </div>

            </div>
        {% endfor %}
    </div>
{% endblock %}