blog/urls.py
from django.urls import path
from django.urls.conf import include

from blog.views import article_list_view, article_detail_view, home_view, article_create_view, tag_list_view, \
    tag_detail_view, tag_create_view, tag_edit_view, tag_delete_view, topic_list_view, topic_create_view, \
    topic_detail_view, topic_edit_view, topic_delete_view, article_like_count_view, article_dislike_count_view, \
    toggle_dislike_view, toggle_like_view, article_archive_view, article_edit_view, article_view_count_view, \
    article_comments_view, article_add_comment_view, article_series_list_view, \
    article_series_detail_view, article_series_get_next_sequence_number_view

app_name = 'blog'

urlpatterns = [
    path('', home_view, name='index'),
    path('articles/', include([
        path('', article_list_view, name='article_list'),
        path('create', article_create_view, name='article_create'),
        path('<str:slug>/',
             include([
                 path('', article_detail_view, name='article_detail'),
                 path('edit', article_edit_view, name='article_edit'),
                 path('archive', article_archive_view, name='article_archive'),
                 path('like_count', article_like_count_view, name='article_like_count'),
                 path('dislike_count', article_dislike_count_view, name='article_dislike_count'),
                 path('toggle_like/', toggle_like_view, name='toggle_like'),
                 path('toggle_dislike/', toggle_dislike_view, name='toggle_dislike'),
                 path('view_count/', article_view_count_view, name='article_view_count'),
                 path('comments', article_comments_view, name='article_comments'),
                 path('add_comment', article_add_comment_view, name='article_add_comment')

             ])
             ),
        path('article_series/', include([
            path('', article_series_list_view, name='article_series_list'),
            path('<str:slug>/', include([
                path('', article_series_detail_view, name='article_series_detail'),
                path('get_next_sequence_number', article_series_get_next_sequence_number_view,
                     name='article_series_get_next_sequence_number')
            ]))
        ])),
        path('tags/', include([
            path('', tag_list_view, name='tag_list'),
            path('create', tag_create_view, name='tag_create'),
            path('<str:slug>/', include([
                path('', tag_detail_view, name='tag_detail'),
                path('edit', tag_edit_view, name='tag_edit'),
                path('delete', tag_delete_view, name='tag_delete'),
            ]))
        ])),
        path('topics/', include([
            path('', topic_list_view, name='topic_list'),
            path('create', topic_create_view, name='topic_create'),
            path('<str:slug>/', include([
                path('', topic_detail_view, name='topic_detail'),
                path('edit', topic_edit_view, name='topic_edit'),
                path('delete', topic_delete_view, name='topic_delete'),
            ]))
        ]))
    ]))
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('content.urls', namespace='content')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('arcus/', include('arcus.urls', namespace='arcus')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('users/', include('django.contrib.auth.urls', )),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'schir.dev admin'

common/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_currentuser.db.models import CurrentUserField


class BaseModel(models.Model):
    created_at = models.DateTimeField(verbose_name=_('Created At'), auto_now_add=True)
    edited_at = models.DateTimeField(verbose_name=_('Edited At'), auto_now=True)
    creator = CurrentUserField(verbose_name=_('Creator'), on_update=False, on_delete=models.CASCADE,
                               related_name='created_%(class)s')
    editor = CurrentUserField(verbose_name=_('Editor'), on_update=True, on_delete=models.CASCADE,
                              related_name='edited_%(class)s')

    class Meta:
        abstract = True
        indexes = [
            models.Index(fields=['created_at']),
            models.Index(fields=['edited_at']),
            models.Index(fields=['creator']),
            models.Index(fields=['editor']),
        ]
        ordering = ['-created_at']

common/templates/cotton/button.html
{% load active_link_tags %}
<c-vars
    type="button"
    variant="primary"
    size="medium"
    extra_classes=""
    icon=""
>
</c-vars>

<button type="{{ type }}" {{ attrs }}
    class="font-normal ease-in-out duration-500 transition-all {{ extra_classes }}
        {% if disabled %} opacity-50 cursor-not-allowed {% endif %}
        {% if size == 'small' %} px-2 py-1 text-sm
        {% elif size == 'large' %} px-6 py-3 text-lg
        {% else %} px-4 py-2 text-base {% endif %}
        {% if variant == 'primary' %}
            text-skin-link hover:text-skin-link-inverted
        {% elif variant == 'secondary' %}
            text-skin-secondary/80 hover:text-skin-secondary
        {% endif %}">
    {% if icon %}
        <c-component is="icons.{{ icon }}" class="mr-2" />
    {% endif %}
    {{ slot }}
</button>

common/templates/cotton/card.html
<div class="p-8 rounded-lg space-y-8 bg-skin-base hover:bg-skin-accent transition-all duration-300 hover:shadow-md">
    <h2 class="text-3xl font-semibold">{{ title }}</h2>
    <div>
        {{ content }}

    </div>
    <div>

        {{ actions }}
    </div>
</div>

common/templates/cotton/navbar.html
{% load static %}
<nav class="bg-skin-surface fixed top-0 z-50 shadow-md h-16 w-full flex justify-center items-center px-4 sm:px-8 lg:px-16"
     x-data="{ menu: { open: false, isSpinning: false } }">
    <!-- Hamburger button for mobile screens -->
    <button
            class="sm:hidden text-skin-secondary/80 hover:text-skin-secondary font-normal ease-in-out duration-500 transition-all"
            @click="menu.open = !menu.open; menu.isSpinning = true; setTimeout(() => menu.isSpinning = false, 500)"
    >
        <div :class="{ 'spin-fast': menu.isSpinning }">
            <c-icons.menu/>
        </div>
    </button>

    <!-- Container for responsive flex layout -->
    <div class="flex w-full justify-between items-center container space-x-3">

        <!-- Left section with navbar items, hidden by default on mobile -->
        <div class="flex-1 space-x-3 items-center hidden sm:flex">
            {{ left }}
            {% for page in navbar_items %}
                <c-nav-link href="#{{ page.slug }}">{{ page.title }}</c-nav-link>
            {% endfor %}
            <c-nav-link href="{% url 'content:index' %}">Portfolio</c-nav-link>
            <c-nav-link href="{% url 'arcus:index' %}">Arcus</c-nav-link>
            <c-nav-link href="{% url 'blog:index' %}">Blog</c-nav-link>
            <c-nav-link href="{% url 'content:index' %}">Portfolio</c-nav-link>
            <c-nav-link href="{% url 'tools:index' %}">Tools</c-nav-link>
        </div>

        <!-- Middle section for centered items, hidden by default on mobile -->
        <div class="hidden sm:block">
            {{ middle }}
        </div>

        <!-- Right section with icons and other nav items -->
        <div class="flex items-center space-x-3">
            {{ right }}
            {% if request.user.is_authenticated %}
            <c-button hx-post="{% url 'logout' %}" type="submit">Logout</c-button>
            {% else %}
            {% endif %}
            <c-nav-link variant="nav" href="{% url 'blog:article_create' %}">
                <c-icons.plus/>
            </c-nav-link>
            <c-nav-link variant="nav" href="https://github.com/schir2">
                <c-icons.github/>
            </c-nav-link>
            <c-icons.sun
                    extra_classes="text-yellow-500 cursor-pointer"
                    x-show="theme === 'dark'"
                    @click="toggleTheme()"
            />

            <!-- Moon icon for dark mode, rotating and scaling when switching -->
            <c-icons.moon
                    extra_classes="text-purple-500 cursor-pointer"
                    x-show="theme === 'light'"
                    @click="toggleTheme()"
            />
        </div>
    </div>

    <!-- Mobile Menu - visible when toggled open -->
    <div x-show="menu.open"
         class="absolute top-16 left-0 w-full bg-skin-surface shadow-md sm:hidden flex flex-col items-start space-y-2 p-4"
         @click.away="menu.open = false">
        {{ left }}
        {% for page in navbar_items %}
            <c-nav-link href="#{{ page.slug }}">{{ page.title }}</c-nav-link>
        {% endfor %}
        <c-nav-link href="{% url 'content:index' %}">Portfolio</c-nav-link>
        <c-nav-link href="{% url 'arcus:index' %}">Arcus</c-nav-link>
        <c-nav-link href="{% url 'blog:index' %}">Blog</c-nav-link>
        <c-nav-link href="{% url 'content:index' %}">Portfolio</c-nav-link>
        <c-nav-link href="{% url 'tools:index' %}">Tools</c-nav-link>
    </div>
</nav>