arcus/urls.py
from django.urls import path, include

from .views import (
    project_list_view, project_detail_view, project_create_view, project_edit_view, project_delete_view,
    task_list_view, task_detail_view, task_create_view, task_edit_view, task_delete_view,
    tag_list_view, tag_detail_view, tag_create_view, tag_edit_view, tag_delete_view,
    section_list_view, section_detail_view, section_create_view, section_edit_view, section_delete_view, index_view,
    project_toggle_star, project_starred_list_sidenav
)

app_name = 'arcus'

project_patterns = ([
    path('', project_list_view, name='project_list'),
    path('project_starred_list_sidenav', project_starred_list_sidenav, name='project_starred_list_sidenav'),
    path('create/', project_create_view, name='project_create'),
    path('<int:pk>/', include([
        path('', project_detail_view, name='project_detail'),
        path('edit/', project_edit_view, name='project_edit'),
        path('star/', project_toggle_star, name='project_toggle_star'),

        path('delete/', project_delete_view, name='project_delete'),
    ])),
])

task_patterns = ([
    path('', task_list_view, name='task_list'),
    path('create/', task_create_view, name='task_create'),
    path('<int:pk>/', include([
        path('', task_detail_view, name='task_detail'),
        path('edit/', task_edit_view, name='task_edit'),
        path('delete/', task_delete_view, name='task_delete'),
    ])),
])

tag_patterns = ([
    path('', tag_list_view, name='tag_list'),
    path('create/', tag_create_view, name='tag_create'),
    path('<int:pk>/', include([
        path('', tag_detail_view, name='tag_detail'),
        path('edit/', tag_edit_view, name='tag_edit'),
        path('delete/', tag_delete_view, name='tag_delete'),
    ])),
])

section_patterns = ([
    path('', section_list_view, name='section_list'),
    path('create/', section_create_view, name='section_create'),
    path('<int:pk>/', include([
        path('', section_detail_view, name='section_detail'),
        path('edit/', section_edit_view, name='section_edit'),
        path('delete/', section_delete_view, name='section_delete'),
    ])),
])

urlpatterns = [
    path('', index_view, name='index'),
    path('projects/', include(project_patterns)),
    path('tasks/', include(task_patterns)),
    path('tags/', include(tag_patterns)),
    path('sections/', include(section_patterns)),
]

blog/urls.py
from django.urls import path
from django.urls.conf import include

from blog.views import article_list_view, article_detail_view, home_view, article_create_view, tag_list_view, \
    tag_detail_view, tag_create_view, tag_edit_view, tag_delete_view, topic_list_view, topic_create_view, \
    topic_detail_view, topic_edit_view, topic_delete_view, article_like_count_view, article_dislike_count_view, \
    toggle_dislike_view, toggle_like_view, article_archive_view, article_edit_view, article_view_count_view, \
    article_comments_view, article_add_comment_view, article_series_list_view, \
    article_series_detail_view, article_series_get_next_sequence_number_view

app_name = 'blog'

urlpatterns = [
    path('', home_view, name='index'),
    path('articles/', include([
        path('', article_list_view, name='article_list'),
        path('create', article_create_view, name='article_create'),
        path('<str:slug>/',
             include([
                 path('', article_detail_view, name='article_detail'),
                 path('edit', article_edit_view, name='article_edit'),
                 path('archive', article_archive_view, name='article_archive'),
                 path('like_count', article_like_count_view, name='article_like_count'),
                 path('dislike_count', article_dislike_count_view, name='article_dislike_count'),
                 path('toggle_like/', toggle_like_view, name='toggle_like'),
                 path('toggle_dislike/', toggle_dislike_view, name='toggle_dislike'),
                 path('view_count/', article_view_count_view, name='article_view_count'),
                 path('comments', article_comments_view, name='article_comments'),
                 path('add_comment', article_add_comment_view, name='article_add_comment')

             ])
             ),
        path('article_series/', include([
            path('', article_series_list_view, name='article_series_list'),
            path('<str:slug>/', include([
                path('', article_series_detail_view, name='article_series_detail'),
                path('get_next_sequence_number', article_series_get_next_sequence_number_view,
                     name='article_series_get_next_sequence_number')
            ]))
        ])),
        path('tags/', include([
            path('', tag_list_view, name='tag_list'),
            path('create', tag_create_view, name='tag_create'),
            path('<str:slug>/', include([
                path('', tag_detail_view, name='tag_detail'),
                path('edit', tag_edit_view, name='tag_edit'),
                path('delete', tag_delete_view, name='tag_delete'),
            ]))
        ])),
        path('topics/', include([
            path('', topic_list_view, name='topic_list'),
            path('create', topic_create_view, name='topic_create'),
            path('<str:slug>/', include([
                path('', topic_detail_view, name='topic_detail'),
                path('edit', topic_edit_view, name='topic_edit'),
                path('delete', topic_delete_view, name='topic_delete'),
            ]))
        ]))
    ]))
]

content/urls.py
from django.urls import path
from django.urls.conf import include

from content.views import index_view, contact_message_form_view

app_name = 'content'

urlpatterns = [
    path('', index_view, name='index'),
    path('forms/', include([
        path('contact_message', contact_message_form_view, name='contact_message_form'),
    ]))
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('content.urls', namespace='content')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('arcus/', include('arcus.urls', namespace='arcus')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('users/', include('django.contrib.auth.urls', )),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'schir.dev admin'

content/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from common.models import BaseModel
from content.storages import OverwriteStorage


class Company(BaseModel):
    name = models.CharField(verbose_name=_("Name"), max_length=255)
    url = models.URLField(verbose_name=_("URL"), blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = _('Companies')


class ContactMessage(BaseModel):
    name = models.CharField(verbose_name=_('Name'), max_length=100)
    email = models.EmailField(verbose_name=_('Email'))
    subject = models.CharField(verbose_name=_('Subject'), max_length=100)
    message = models.TextField(verbose_name=_('Message'))

    def __str__(self):
        return f'{self.name}, {self.email}, {self.subject}'

    class Meta:
        ordering = ('-created_at',)


class Page(BaseModel):
    title = models.CharField(verbose_name=_('Title'), max_length=200)
    slug = models.SlugField(verbose_name=_('Slug'), unique=True)
    content = models.TextField(verbose_name=_('Content'))
    show_on_homepage = models.BooleanField(verbose_name=_('Show on homepage'), default=False)
    show_in_navbar = models.BooleanField(verbose_name=_('Show on navigation'), default=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']


class Project(BaseModel):
    name = models.CharField(verbose_name=_('Name'), max_length=255)
    description = models.TextField(verbose_name=_('Description'), )
    skills = models.ManyToManyField('content.Skill', verbose_name=_('Skills'), related_name='projects')
    company = models.ForeignKey('Company', verbose_name=_('Company'), max_length=255, on_delete=models.SET_NULL,
                                null=True, related_name='projects', blank=True)
    year = models.PositiveSmallIntegerField(verbose_name=_('Year'), default=timezone.now().year, )
    image = models.ImageField(verbose_name=_('Image'), upload_to='projects/%Y/%m/%d/', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-year',)


class Skill(BaseModel):
    PROFICIENCY = [
        (1, _('Novice')),
        (2, _('Beginner')),
        (3, _('Competent')),
        (4, _('Proficient')),
        (5, _('Expert')),
    ]

    name = models.CharField(verbose_name=_('Name'), max_length=255)
    icon = models.FileField(_("Icon"), upload_to='icons/', blank=True, null=True, storage=OverwriteStorage())
    proficiency = models.PositiveSmallIntegerField(
        _("Proficiency"),
        choices=PROFICIENCY,
        default=3,
    )
    category = models.ForeignKey(
        'SkillCategory',
        verbose_name=_("Category"),
        related_name='skills',
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-proficiency', 'name']


class SkillCategory(BaseModel):
    name = models.CharField(_("Category Name"), max_length=100)
    icon = models.FileField(_("Icon"), upload_to='category_icons/', blank=True, null=True)
    order = models.PositiveSmallIntegerField(_("Order"), default=1)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['order', 'name']
        verbose_name_plural = _('Skill Categories')

content/models/post.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

from content.models.base import BaseModel

User = get_user_model()


class Post(BaseModel):
    title = models.CharField(verbose_name=_('Title'), max_length=200)
    slug = models.SlugField(verbose_name=_('Slug'), unique=True)
    content = models.TextField(verbose_name=_('Content'), )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']

content/forms/contact_message_forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox

from content.models import ContactMessage


class ContactMessageForm(forms.ModelForm):
    SUBJECT_CHOICES = [
        ('contract', 'Contract Work'),
        ('full_time', 'Full-Time Opportunity'),
        ('general_inquiry', 'General Inquiry'),
    ]

    name = forms.CharField(
        label="Full Name",
        help_text="Please enter your full name or the name of your organization.",
        widget=forms.TextInput(attrs={'placeholder': 'Full Name or Organization Name'})
    )
    email = forms.EmailField(
        label="Email Address",
        help_text="Enter your business or contact email address. We will use this to follow up.",
        widget=forms.EmailInput(attrs={'placeholder': 'Your Email Address'})
    )
    subject = forms.ChoiceField(
        label="Reason for Contact",
        help_text="Select the type of inquiry.",
        choices=SUBJECT_CHOICES,
        widget=forms.Select(attrs={'type': 'select'})
    )
    message = forms.CharField(
        label="Message",
        help_text="Please provide details about the opportunity, project, or your inquiry. Feel free to include any relevant information or questions.",
        widget=forms.Textarea(attrs={'placeholder': 'Your Message'})
    )
    captcha = ReCaptchaField(
        widget=ReCaptchaV2Checkbox,
        help_text="Prove you're not a robot."
    )

    class Meta:
        model = ContactMessage
        fields = ('name', 'email', 'subject', 'message')

content/views.py
from django.contrib.auth.decorators import login_not_required
from django.shortcuts import render
from django.views.generic import ListView

from content.forms.contact_message_forms import ContactMessageForm
from content.models import Project, SkillCategory, Page


@login_not_required
def index_view(request):
    context = {}
    form = ContactMessageForm
    projects = Project.objects.all()
    context['projects'] = projects
    context['pages'] = Page.objects.filter(show_on_homepage=True)
    context['skill_categories'] = SkillCategory.objects.all()
    context['form'] = form()
    return render(request, 'content/home.html', context=context)


@login_not_required
def contact_message_form_view(request):
    context = {}

    if request.method == 'POST':
        form = ContactMessageForm(request.POST)
        if form.is_valid():
            form.save()
            form = ContactMessageForm()
            context['message'] = 'Your message was successfully sent'
        form = form
    else:
        form = ContactMessageForm()

    context['form'] = form

    if request.htmx:
        return render(request, template_name='content/partials/contact_message_form.html', context=context)
    return render(request, 'content/contact_message_form.html', context=context)

content/templates/cotton/footer.html
<footer class="bg-skin-base text-xl border-solid border-2 fixed bottom-0 w-screen">
    <div class="container p-6 mx-auto">
        <div class="flex justify-center gap-3 items-center">
            <c-link href={% url 'content:project_list' %}>Projects</c-link>
            <c-link href={% url 'content:bio' %}>Bio</c-link>
            <c-link href={% url 'content:contact' %}>Contact</c-link>
            <c-link href={% url 'content:about' %}>About</c-link>
            <a href="#"
               class="transition-colors duration-3000 hover:text-blue-500"
               aria-label="Facebook">
                <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                            d="M2.00195 12.002C2.00312 16.9214 5.58036 21.1101 10.439 21.881V14.892H7.90195V12.002H10.442V9.80204C10.3284 8.75958 10.6845 7.72064 11.4136 6.96698C12.1427 6.21332 13.1693 5.82306 14.215 5.90204C14.9655 5.91417 15.7141 5.98101 16.455 6.10205V8.56104H15.191C14.7558 8.50405 14.3183 8.64777 14.0017 8.95171C13.6851 9.25566 13.5237 9.68693 13.563 10.124V12.002H16.334L15.891 14.893H13.563V21.881C18.8174 21.0506 22.502 16.2518 21.9475 10.9611C21.3929 5.67041 16.7932 1.73997 11.4808 2.01722C6.16831 2.29447 2.0028 6.68235 2.00195 12.002Z">
                    </path>
                </svg>
            </a>

            <a href="#"
               class="text-gray-600 transition-colors duration-300 hover:text-blue-500"
               aria-label="Github">
                <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                            d="M12.026 2C7.13295 1.99937 2.96183 5.54799 2.17842 10.3779C1.395 15.2079 4.23061 19.893 8.87302 21.439C9.37302 21.529 9.55202 21.222 9.55202 20.958C9.55202 20.721 9.54402 20.093 9.54102 19.258C6.76602 19.858 6.18002 17.92 6.18002 17.92C5.99733 17.317 5.60459 16.7993 5.07302 16.461C4.17302 15.842 5.14202 15.856 5.14202 15.856C5.78269 15.9438 6.34657 16.3235 6.66902 16.884C6.94195 17.3803 7.40177 17.747 7.94632 17.9026C8.49087 18.0583 9.07503 17.99 9.56902 17.713C9.61544 17.207 9.84055 16.7341 10.204 16.379C7.99002 16.128 5.66202 15.272 5.66202 11.449C5.64973 10.4602 6.01691 9.5043 6.68802 8.778C6.38437 7.91731 6.42013 6.97325 6.78802 6.138C6.78802 6.138 7.62502 5.869 9.53002 7.159C11.1639 6.71101 12.8882 6.71101 14.522 7.159C16.428 5.868 17.264 6.138 17.264 6.138C17.6336 6.97286 17.6694 7.91757 17.364 8.778C18.0376 9.50423 18.4045 10.4626 18.388 11.453C18.388 15.286 16.058 16.128 13.836 16.375C14.3153 16.8651 14.5612 17.5373 14.511 18.221C14.511 19.555 14.499 20.631 14.499 20.958C14.499 21.225 14.677 21.535 15.186 21.437C19.8265 19.8884 22.6591 15.203 21.874 10.3743C21.089 5.54565 16.9181 1.99888 12.026 2Z">
                    </path>
                </svg>
            </a>
        </div>
        <div class="flex flex-wrap justify-center gap-3">

        </div>
    </div>
</footer>

content/templates/cotton/nav_link.html
{% load active_link_tags %}
<a {% if href %}href="{{ href }}"{% endif %}
   class="{% active_link href %} text-skin-secondary/80 hover:text-skin-secondary font-normal ease-in-out duration-500 transition-all {{ extra_classes }}">
    {% if icon %}
        <c-component is="icons.{{ icon }}"/>
    {% endif %}
    {{ slot }}
</a>

content/templates/cotton/skill_item.html
<div id="skillItem{{ skill.pk }}">
    <img src="{{ skill.icon }}">
</div>